language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install pkg-config
  - sudo apt-get install linux-libc-dev
  - sudo apt-get install qttools5-dev-tools
  - sudo apt-get install qtdeclarative5-dev
  - sudo apt-get install libqt5svg5-dev
  - sudo apt-get install libgstreamer-plugins-base1.0-dev
  - sudo apt-get install libpulse-dev
  - sudo apt-get install libv4l-dev

script:
  - qmake -qt=5 Webcamoid.pro USE_GSTREAMER=1
  - make

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
