language: cpp

cache:
  ccache: true
  apt: true
  timeout: 1000

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
      - QTVER=57
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env:
      - QTVER=57
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
      - USE_GSTREAMER=false
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
      - USE_GSTREAMER=true

before_install: |
  if [ "${TRAVIS_OS_NAME}" = linux ]; then
    sudo add-apt-repository --yes ppa:beineri/opt-qt${QTVER}-trusty
    sudo add-apt-repository --yes ppa:mc3man/trusty-media
    sudo add-apt-repository --yes ppa:dan-witt/gstreamer
    sudo apt-get update -qq
  elif [ "${TRAVIS_OS_NAME}" = osx ]; then
    brew update
    brew upgrade
  fi

install: |
  if [ "${TRAVIS_OS_NAME}" = linux ]; then
    sudo apt-get -y install pkg-config
    sudo apt-get -y install linux-libc-dev
    sudo apt-get -y install qt${QTVER}tools
    sudo apt-get -y install qt${QTVER}declarative
    sudo apt-get -y install qt${QTVER}svg
    sudo apt-get -y install libgstreamer-plugins-base1.0-dev
    sudo apt-get -y install libpulse-dev
    sudo apt-get -y install libv4l-dev
  elif [ "${TRAVIS_OS_NAME}" = osx ]; then
    brew install ccache pkg-config qt5 ffmpeg gstreamer gst-plugins-base libuvc
  fi

before_script: |
  if [ "${TRAVIS_OS_NAME}" = linux ]; then
    source /opt/qt${QTVER}/bin/qt${QTVER}-env.sh
    if [ "${CXX}" = g++ ]; then
      export QMAKESPEC=linux-g++
    elif [ "${CXX}" = clang++ ]; then
      export QMAKESPEC=linux-clang
    fi
  elif [ "${TRAVIS_OS_NAME}" = osx ]; then
    brew link --force qt5
    if [ "${USE_GSTREAMER}" = false ]; then
        FFVER=$(ffmpeg -version | head -n 1 | awk '{printf "%s", $3}')
    else
        GSTVER=$(gst-inspect-1.0 --version | head -n 1 | awk '{printf "%s", $3}')
    fi
    if [ "${CXX}" = g++ ]; then
      export QMAKESPEC=macx-g++
    elif [ "${CXX}" = clang++ ]; then
      export QMAKESPEC=macx-clang
    fi
  fi
script: |
  [[ "${CXX}" = clang++ ]] && UNUSEDARGS="-Qunused-arguments" || UNUSEDARGS=""
  COMPILER="ccache ${CXX} ${UNUSEDARGS}"
  if [ "${TRAVIS_OS_NAME}" = linux ]; then
    qmake Webcamoid.pro \
        QMAKE_CXX="${COMPILER}" \
        USE_GSTREAMER=1
  elif [ "${TRAVIS_OS_NAME}" = osx ]; then
    if [ "${USE_GSTREAMER}" = false ]; then
        qmake Webcamoid.pro \
            QMAKE_CXX="${COMPILER}" \
            FFMPEGINCLUDES="/usr/local/Cellar/ffmpeg/${FFVER}/include" \
            FFMPEGLIBS=-L"/usr/local/Cellar/ffmpeg/${FFVER}/lib" \
            FFMPEGLIBS+=-lavcodec \
            FFMPEGLIBS+=-lavdevice \
            FFMPEGLIBS+=-lavformat \
            FFMPEGLIBS+=-lavutil \
            FFMPEGLIBS+=-lswresample \
            FFMPEGLIBS+=-lswscale
    else
        qmake Webcamoid.pro \
            QMAKE_CXX="${COMPILER}" \
            USE_GSTREAMER=1 \
            GSTREAMERINCLUDES="/usr/local/Cellar/gstreamer/${GSTVER}/include/gstreamer-1.0" \
            GSTREAMERINCLUDES+="/usr/local/Cellar/gst-plugins-base/${GSTVER}_1/include/gstreamer-1.0" \
            GSTREAMERLIBS=-L"/usr/local/Cellar/gstreamer/${GSTVER}/lib" \
            GSTREAMERLIBS+=-L"/usr/local/Cellar/gst-plugins-base/${GSTVER}_1/lib" \
            GSTREAMERLIBS+=-lgstapp-1.0 \
            GSTREAMERLIBS+=-lgstaudio-1.0 \
            GSTREAMERLIBS+=-lgstvideo-1.0 \
            GSTREAMERLIBS+=-lgstbase-1.0 \
            GSTREAMERLIBS+=-lgstpbutils-1.0 \
            GSTREAMERLIBS+=-lgstreamer-1.0 \
            GSTREAMERLIBS+=-lgobject-2.0 \
            GSTREAMERLIBS+=-lglib-2.0
    fi
  fi
  make

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
