version: 7.2.1.{build}-{branch}
os: MinGW

platform:
  - x86

build:
  parallel: true
  verbosity: detailed

configuration:
  - debug
  - release

branches:
  only:
  - master

environment:
  global:
    FFMPEG_VERSION: 3.2
    GSTREAMER_VERSION: 1.10.2
    QTDIR: C:\Qt\5.7\mingw53_32
    QMAKESPEC: win32-g++
    MAKETOOL: mingw32-make

  matrix:
    - TOOLSDIR: C:\Qt\Tools\mingw482_32
    - TOOLSDIR: C:\Qt\Tools\mingw491_32
    - TOOLSDIR: C:\Qt\Tools\mingw492_32
    - TOOLSDIR: C:\Qt\Tools\mingw530_32
    - QTDIR: C:\Qt\5.7\msvc2013
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc2013
      VSVER: 12
      MAKETOOL: jom
    - PLATFORM: x64
      QTDIR: C:\Qt\5.7\msvc2013_64
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc2013
      VSVER: 12
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.7\msvc2015
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc2015
      VSVER: 14
      MAKETOOL: jom
    - PLATFORM: x64
      QTDIR: C:\Qt\5.7\msvc2015_64
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc2015
      VSVER: 14
      MAKETOOL: jom

install:
  - ports\ci\appveyor\install.bat

build_script:
  - ports\ci\appveyor\build.bat

cache:
  - ../webcamoid-shadow-build -> libAvKys/libAvKys.pro
  - ../webcamoid-shadow-build -> appveyor.yml
  - ffmpeg-%FFMPEG_VERSION%-win32-dev.zip
  - gstreamer-1.0-devel-x86-%GSTREAMER_VERSION%.msi

notifications:
  - provider: Email
    to:
      - hipersayan.x@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
