version: 7.2.1.{build}-{branch}
os: MinGW

platform:
  - x86

build:
  verbosity: detailed

configuration:
  - debug
  - release

branches:
  only:
  - master

environment:
  global:
    FFMPEG_VERSION: 3.2
    GSTREAMER_VERSION: 1.10.2
    QTDIR: C:\Qt\5.7\mingw53_32
    QMAKESPEC: win32-g++
    MAKETOOL: mingw32-make

  matrix:
    - MINGW: C:\Qt\Tools\mingw482_32
    - MINGW: C:\Qt\Tools\mingw491_32
    - MINGW: C:\Qt\Tools\mingw492_32
    - MINGW: C:\Qt\Tools\mingw530_32
    - QTDIR: C:\Qt\5.7\msvc2013
      QMAKESPEC: win32-msvc2013
      MAKETOOL: jom
    - PLATFORM: x64
      QTDIR: C:\Qt\5.7\msvc2013_64
      QMAKESPEC: win32-msvc2013
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.7\msvc2015
      QMAKESPEC: win32-msvc2015
      MAKETOOL: jom
    - PLATFORM: x64
      QTDIR: C:\Qt\5.7\msvc2015_64
      QMAKESPEC: win32-msvc2015
      MAKETOOL: jom

install:
  - ports\ci\appveyor\install.bat

build_script:
  - ports\ci\appveyor\build.bat

cache:
  - ffmpeg-%FFMPEG_VERSION%-win32-dev.zip
  - gstreamer-1.0-devel-x86-%GSTREAMER_VERSION%.msi

notifications:
  - provider: Email
    to:
      - hipersayan.x@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
